// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CadastroPessoa.DATA.Models
{
    [Table("ENDERECO")]
    public partial class Endereco
    {
        public Endereco()
        {
            Pessoa = new HashSet<Pessoa>();
        }

        [Key]
        [Column("ID_ENDERECO")]
        public int IdEndereco { get; set; }
        [Required]
        [Column("LONGRADOURO")]
        [StringLength(256)]
        public string Longradouro { get; set; }
        [Column("NUMERO")]
        public int Numero { get; set; }
        [Column("CEP")]
        public int Cep { get; set; }
        [Required]
        [Column("BAIRRO")]
        [StringLength(50)]
        public string Bairro { get; set; }
        [Required]
        [Column("CIDADE")]
        [StringLength(30)]
        public string Cidade { get; set; }
        [Required]
        [Column("ESTADO")]
        [StringLength(20)]
        public string Estado { get; set; }

        [InverseProperty("EnderecoNavigation")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}