// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CadastroPessoa.DATA.Models
{
    [Table("PESSOA_TELEFONE")]
    public partial class PessoaTelefone
    {
        [Key]
        [Column("ID_PESSOA_FK")]
        public int IdPessoaFk { get; set; }
        [Column("ID_TELEFONE_FK")]
        public int IdTelefoneFk { get; set; }

        [ForeignKey(nameof(IdPessoaFk))]
        [InverseProperty(nameof(Pessoa.PessoaTelefone))]
        public virtual Pessoa IdPessoaFkNavigation { get; set; }
        [ForeignKey(nameof(IdTelefoneFk))]
        [InverseProperty(nameof(Telefone.PessoaTelefone))]
        public virtual Telefone IdTelefoneFkNavigation { get; set; }
    }
}