// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CadastroPessoa.DATA.Models
{
    [Table("PESSOA")]
    public partial class Pessoa
    {
        [Key]
        [Column("ID_PESSOA")]
        public int IdPessoa { get; set; }
        [Required]
        [Column("NOME")]
        [StringLength(50)]
        public string Nome { get; set; }
        [Required]
        [Column("CPF")]
        [StringLength(100)]
        public string Cpf { get; set; }
        [Column("ENDERECO")]
        public int Endereco { get; set; }

        [ForeignKey(nameof(Endereco))]
        [InverseProperty("Pessoa")]
        public virtual Endereco EnderecoNavigation { get; set; }
        [InverseProperty("IdPessoaFkNavigation")]
        public virtual PessoaTelefone PessoaTelefone { get; set; }
    }
}