// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CadastroPessoa.DATA.Models
{
    [Table("TELEFONE_TIPO")]
    public partial class TelefoneTipo
    {
        public TelefoneTipo()
        {
            Telefone = new HashSet<Telefone>();
        }

        [Key]
        [Column("ID_TIPO_TEL")]
        public int IdTipoTel { get; set; }
        [Required]
        [Column("TIPO")]
        [StringLength(10)]
        public string Tipo { get; set; }

        [InverseProperty("TipoNavigation")]
        public virtual ICollection<Telefone> Telefone { get; set; }
    }
}